name: Run Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run script
        run: python scraper.py

      - name: Commit result
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add output/playlist.m3u
          git commit -m "update playlist" || echo "no change"
          git push
